### ISSUE TITLE
ZOPIM not work

### ISSUE THREAD

**Issue by fpleme** [turbolinks/turbolinks-classic#131]
The chat window doesn't re-render when you clink in some link. 

www.zopim.com

any suggestion?

**Comment by mupty** [comment]
@infernalmaster : what do you mean about `so it triggers multiple times`? Does it init alot of socket to zopim?

I implemented as 2 above ways, but it init one socket connect each time I click to other page. Is that correct?

**Comment by infernalmaster** [comment]
As you know,  turbolinks does not reload all page, but just replaces page <body> content with new. So it automatically executes inlined into the page body script `$(window).on('page:change.zopim', zopim_chat);`. So after third page change this script will executes 3 times and you will have 3 registered callbacks on `'page:change.zopim`. So to prevent this I removes all handlers every time with this `.off('page:change.zopim')`.

@mupty you are right about socket connection, because this script does not destroy previous zopim instance with closing connection. Because there is no such functionality there. 

So all previous zopim instances are still alive (and sockets too) but it views are removed by turbolinks page reload. And my solution is dirty hack. 

So now I see better solution:
1. init zopim only once (do it in page header)
2. before page change (`page:before-change`) remove zopim view from DOM but keep it in memory
3. after page change (`page:change`) insert zopim view from memory into right place in DOM

**Comment by mupty** [comment]
@infernalmaster: Thank you for your reply. I will try to implement base on your idea.

**Comment by mupty** [comment]
@infernalmaster : I implemented as your above idea, but it did not work fine. The reason is: zopim uses an iframe to display chat content, so, when I:
```
2. before page change (page:before-change) remove zopim view from DOM but keep it in memory
3. after page change (page:change) insert zopim view from memory into right place in DOM
```, all events of elements would not bound any more. 

Below snippet code works fine with`insert zopim view from memory into right place in DOM`, but cannot work with events on each elements as before:
 
```
var zopimViewOuterHtml = [];
var zopimViewInnerHtml = [];
function zopimChat() {
    $('[__jx__id]').remove();
    window.$zopim || (function (d, s) {
        var z = $zopim = function (c) {
            z._.push(c)
        }, $ = z.s = d.createElement(s), e = d.body.getElementsByTagName(s)[0];
        z.set = function (o) {
            z.set._.push(o)
        };
        z._ = [];
        z.set._ = [];
        $.async = !0;
        $.setAttribute('charset', 'utf-8');
        $.src = '//v2.zopim.com/?49QIiqblKryIH65v4r4DV4K72UWIPZtI';
        z.t = +new Date;
        $.type = 'text/javascript';
        e.parentNode.insertBefore($, e);
    })(document, 'script');

    applyZopimViewContent();
}

function getZopimViewContent() {
    zopimViewOuterHtml = [];
    zopimViewInnerHtml = [];
    $.each($('.zopim'), function (index, ele) {
        zopimViewOuterHtml.push(ele.outerHTML);
        zopimViewInnerHtml.push($(ele).find('iframe').contents().find('html').html());
    });
}

function applyZopimViewContent() {
    zopimViewInnerHtml = zopimViewInnerHtml.reverse();
    zopimViewOuterHtml = zopimViewOuterHtml.reverse();
    $.each(zopimViewOuterHtml, function (index, outer) {
        $('body').prepend(outer);
        $('iframe')[index].contentDocument.write(zopimViewInnerHtml[index]);
    });
}

$(window).on('page:before-change', getZopimViewContent);
$(window).on('page:change', zopimChat);
```

So, I fixed this by define a blank page, that contains only zopim chat box. Then, I call it on iframe on page where I want to chat box appears. This blank page could be served as static html page easily.

Detail:

* html page:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
  <title><%= "#{system_name} - サポート" %></title>

  
  <script type="text/javascript">
    window.$zopim||(function(d,s){var z=$zopim=function(c){
      z._.push(c)},$=z.s=
      d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
      _.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
      $.src='//v2.zopim.com/?YOUR_KEY';z.t=+new Date;$.
        type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
  </script>
  
</head>

<body>
</body>
</html>

```

and on page where I where I want to chat box appears:

```
<div class="support-chat">
  <iframe src="path_to_above_html_file" class="iframe-support-chat"></iframe>
</div>
```

```
.support-chat {
  position: fixed;
  bottom: 0;
  right: 0;
  max-width: 290px;
  max-height: 400px;
  overflow: hidden;
  z-index: 3;
}

.iframe-support-chat {
  height: 400px;
  width: 290px;
  overflow: hidden;
  border: none;
}
```
