### ISSUE TITLE
A form with remote: true sends more than one ajax request.

### ISSUE THREAD

**Issue by vysakh0** [turbolinks/turbolinks-classic#153]
Looking at the firebug, this line is the one causing this problem: xhr.send( ( s.hasContent && s.data ) || null ) in jquery.js file;  . Without remote: true, the form works fine with turbolink. And form worked before including turbolink.

**Comment by carlesjove** [comment]
Even though this issue is closed, just say that I got into this problem too, using Rails 4.2. Removing Turbolinks solved the issue. I tried to reproduce the situation in integration tests (using Capybara), unsuccessfully. It seems to happen only in the browser.
My app is really simple (yet) because I'm just starting to build it, so it's almost barebones, and even though it is a private project of mine, I wouldn't mind sharing the code base with any of you if this can help fixing the issue.

**Comment by johannesE** [comment]
It says here: https://github.com/kossnocorp/jquery.turbolinks

If you find that some events are being fired multiple times after using jQuery Turbolinks, you may have been binding your document events inside a $(function()) block. For instance, this example below can be a common occurrence and should be avoided:

/* BAD: don't bind 'document' events while inside $()! */
$(function() {
  $(document).on('click', 'button', function() { ... })
});

You should be binding your events outside a $(function()) block. This will ensure that your events will only ever be bound once.

/* Good: events are bound outside a $() wrapper. */
$(document).on('click', 'button', function() { ... })

Hope this helps..
