### ISSUE TITLE
Bootstrap Nav Bar - Dropdown Menus

### ISSUE THREAD

**Issue by ziyan-junaideen** [turbolinks/turbolinks-classic#319]
I started a new application using `Rails 4.0.1` using `gem 'bootstrap-sass-rails'` for bootstrap V3. After getting the navigation ready, I noticed that the menu didn't drop-down after first navigation.

Today I came across a rails cast video about Rails 4 features by Ryan, and I noticed `Turbolinks` which I noticed in the JavaScript file. I removed Turbolinks and it works alright. 

Then I added Jquery.Turbolinks gem as suggested with Turbolinks enabled again as previous. The result was the same, after navigating away the first time, the menu is no longer usable.

I didn't get to try it with any other link, because I only have a menu in the page. It seems very promising and would be great if it works with Bootstrap.

**Comment by oppih** [comment]
@marcamillion Later on I found myself added two lines of application.js that caused the problem. After I removed one then I just worked!

**Comment by plicjo** [comment]
A less hacky fix would be to add the `jquery-turbolinks` gem.

The reason the dropdowns aren't working is because they are bound to `$(document).ready` instead of `$(document).on('page:change')`, which is what turbolinks uses.

The `jquery-turbolinks` gem will make it so that `ready` calls will also respond to turbolink's `page:change` calls.

Gemfile:

`gem 'jquery-turbolinks'`
Add it to your JavaScript manifest file, in this order:

```
//= require jquery
//= require jquery.turbolinks
//= require jquery_ujs
//
// ... your other scripts here ...
//
//= require turbolinks
```
And it just works!

**Comment by sameerkhanna** [comment]
Another cause for this could be you have your javascript placed at the end of body. It should be in the head. I noticed this when bootstrap dropdowns would work on initial page load, but not after subsequent clicks.

**Comment by colepanike** [comment]
@plicjo Thanks for the tips but I'm finding that I still have the problem. In fact, now the dropdown doesn't work at all, not just after navigating. This issue really aught to be open.

**Comment by bguban** [comment]
Use https://github.com/kossnocorp/jquery.turbolinks/blob/master/README.md to fix this problem
