### ISSUE TITLE
Incompatible with Chrome for iOS

### ISSUE THREAD

**Issue by sstephenson** [turbolinks/turbolinks-classic#82]
There are some pushState-related differences from Mobile Safari in Chrome for iOS that cause Turbolinks not to work. Here's what I've found:
1. `rememberInitialPage` runs on the first call to `visit` in Mobile Safari, but in Chrome for iOS it runs as soon as the page loads.
2. In Mobile Safari, the `window.history.state` access in `rememberCurrentState` reflects the state that was set in the previous call to `replaceState` in `rememberCurrentUrl`. In Chrome for iOS, `window.history.state` is null in `rememberCurrentState`, so `currentState` is null too.
3. Because `currentState` is null in Chrome for iOS on the first call to `visit`, `cacheCurrentPage` fails. If you explicitly call `Turbolinks.visit`, the end result is the page never loads. If you click a link, it will fall back to a full page load.

**Comment by liamzebedee** [comment]
Hey all, has this been closed permanently as a non-fixable issue?

**Comment by liamzebedee** [comment]
Anyone have any idea as to the root cause? [Push.js](https://github.com/liamzebedee/push.js/blob/master/push.js) from the Ratchet framework is able to function in Chrome on iOS (by simply using replaceState), could someone explain why Ratchet needs specific access to window.history.state? I'd be willing to give it a try to fix, Turbolinks is much better :)

**Comment by javan** [comment]
It's worth revisiting the issues Sam outlined in his initial report. If it's working now in the latest Chrome for iOS, we can scope the browser check to older versions.

**Comment by brendon** [comment]
Is this bug/problem/workaround present in Turbolinks 5?
